#!/usr/bin/env sh

# Description: Open images in hovered  directory and thumbnails
#              open hovered image in sxiv or viu and browse other images in the directory
#
# Shell: POSIX compliant
# Author: Arun Prakash Jana

abspath() {
    case "$1" in
        /*) printf "%s\n" "$1";;
        *)  printf "%s\n" "$PWD/$1";;
    esac
}

list_images() {
    find -L "$(dirname "$target")" -maxdepth 1 -type f -iregex \
      '.*\(jpe?g\|bmp\|webp\|svg\|png\|gif\)$' -print0 | sort -z
}

view_dir() {
    target="$(abspath "$2")"
    count="$(list_images | grep -a -m 1 -ZznF "$target" | cut -d: -f1)"

    if [ -n "$count" ]; then
        if [ "$1" = 'sxiv' ]; then
            list_images | xargs -0 "$1" -an "$count" --
        else
            list_images | xargs -0 "$1" -n "$count" --
        fi
    else
        shift
        "$1" -- "$@" # fallback
    fi
}

if [ -z "$1" ] || ! [ -s "$1" ]; then
    printf "empty file"
    read -r _
    exit 1
fi

if [ -f "$1" ]; then
    view_dir sxiv "$1" >/dev/null 2>&1 &
elif [ -d "$1" ] || [ -h "$1" ]; then
    sxiv -aqt "$1" >/dev/null 2>&1 &
fi